title: 'Bitdevsinteriorrr (RP/Sanca/)'
tagline: 'Bitdevsinteriorrr é uma comunidade para os interessados em discutir e participar de pesquisas e desenvolvimento em Bitcoin e projetos relacionados'
enu:
  - {name: 'Sobre', url: '/about'}
  - {name: 'Eventos', url: '/events'}
  - {name: 'Blog', url: '/blog'}
  - {name: 'Meetup', url: 'https://www.meetup.com/bitdevsinteriorrr/', external: true}
  - {name: 'Cities', url: '/cities'}
